### PR TITLE
native module preemptive loading

### LINKED ISSUE #322: Detect when serialport module fails to load
The serialport module is natively compiled so when a different node is used to run the CLI than was used during installation the CLI will fail to run with "the module version expected is 48 and it got 47" or similar.

Detect this situation by preemptively requiring serialport and catching any errors. Display a message to the user to reinstall the CLI in this case.

### PR DESCRIPTION
**Pull request by m-mcgowan**
Loads native modules as part of startup to capture any loading issues. If they fail to load, the user is prompted to reinstall the CLI. fixes #322

### CODE REVIEW

File: src/app/app.js [hunk 1]
```diff
@@ -212,11 +212,33 @@ export class CLI {
...
 		settings.whichProfile();
 		settings.loadOverrides();
 
+		const nativeErrors = this.loadNativeModules(settings.nativeModules);
+		if (nativeErrors.length) {
+			const log = require('./log');
+			for (let error of nativeErrors) {
+				log.error(error);
+			}
+			log.fatal('Please reinstall the CLI again to ensure the module is installed to match the version of node.');
```
Comment (monkbroc) [inline src/app/app.js]: I'd say simply:
Reinstall the CLI by running npm install -g particle-cli

Comment (m-mcgowan) [inline src/app/app.js]: that will work for windows users as well after using the installer?

Comment (monkbroc) [inline src/app/app.js]: People with the installer are not likely to see this error. This also works on Windows.
